//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviePrediction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoviePrediction.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday: .
        /// </summary>
        internal static string BirthdayLabel {
            get {
                return ResourceManager.GetString("BirthdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast:.
        /// </summary>
        internal static string CastLabel {
            get {
                return ResourceManager.GetString("CastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        internal static string CastPageTitle {
            get {
                return ResourceManager.GetString("CastPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account..
        /// </summary>
        internal static string CreateAccountLabel {
            get {
                return ResourceManager.GetString("CreateAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew:.
        /// </summary>
        internal static string CrewLabel {
            get {
                return ResourceManager.GetString("CrewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathday:.
        /// </summary>
        internal static string DeathdayLabel {
            get {
                return ResourceManager.GetString("DeathdayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string FromDateLabel {
            get {
                return ResourceManager.GetString("FromDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hate paperwork, too..
        /// </summary>
        internal static string HatePaperworkLabel {
            get {
                return ResourceManager.GetString("HatePaperworkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryLabel {
            get {
                return ResourceManager.GetString("HistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb profile.
        /// </summary>
        internal static string IMDbProfileLabel {
            get {
                return ResourceManager.GetString("IMDbProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language: .
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingTitle {
            get {
                return ResourceManager.GetString("LoadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string MoviesPageTitle {
            get {
                return ResourceManager.GetString("MoviesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        internal static string NeedHelpLabel {
            get {
                return ResourceManager.GetString("NeedHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to Predix? Sign up now.
        /// </summary>
        internal static string NewToPredixLabel {
            get {
                return ResourceManager.GetString("NewToPredixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        internal static string NowPlayingLabel {
            get {
                return ResourceManager.GetString("NowPlayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just one step and you&apos;re done!.
        /// </summary>
        internal static string OneStepLabel {
            get {
                return ResourceManager.GetString("OneStepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview:.
        /// </summary>
        internal static string OverviewLabel {
            get {
                return ResourceManager.GetString("OverviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth: .
        /// </summary>
        internal static string PlaceOfBirthLabel {
            get {
                return ResourceManager.GetString("PlaceOfBirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular movies.
        /// </summary>
        internal static string PopularMovieLabel {
            get {
                return ResourceManager.GetString("PopularMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular TV.
        /// </summary>
        internal static string PopularTVLabel {
            get {
                return ResourceManager.GetString("PopularTVLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        internal static string PredictionPageTitle {
            get {
                return ResourceManager.GetString("PredictionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date: .
        /// </summary>
        internal static string ReleaseDateLabel {
            get {
                return ResourceManager.GetString("ReleaseDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string ShowMoreLabel {
            get {
                return ResourceManager.GetString("ShowMoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soon.
        /// </summary>
        internal static string SoonLabel {
            get {
                return ResourceManager.GetString("SoonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up to start your unforgettable experience.
        /// </summary>
        internal static string StartExperienceLabel {
            get {
                return ResourceManager.GetString("StartExperienceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string ToDateLabel {
            get {
                return ResourceManager.GetString("ToDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top rated movies.
        /// </summary>
        internal static string TopRatedMovieLabel {
            get {
                return ResourceManager.GetString("TopRatedMovieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top rated TV.
        /// </summary>
        internal static string TopRatedTV {
            get {
                return ResourceManager.GetString("TopRatedTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string TVPageTitle {
            get {
                return ResourceManager.GetString("TVPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for prediction....
        /// </summary>
        internal static string WaitForPredictionText {
            get {
                return ResourceManager.GetString("WaitForPredictionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
